### ISSUE TITLE
Traning cost

### ISSUE THREAD

**Issue by jjihwan** [theAdamColton/vq-clip#3]
Thank you for your great work and for open-sourcing!

Would you please share the rough computational cost(time, GPU, etc...) to train your codebooks(k=64 32 heads, multi-headed)?
It would be great if you could share your email address.

Thanks again!

**Comment by theAdamColton** [comment]
Hi,
I trained all listed models using one 3070ti GPU. I used a batch size of 16,384. This is possible on one GPU because I only train the weights for the quantization adapter network. The original CLIP ViT weights are kept frozen, and the [CLS] embeddings of all images are extracted in an offline preprocessing step.

**Comment by jjihwan** [comment]
Got it, thanks!
